pipeline {

    agent any

    stages {

        stage('Cleanup Workspace') {
            steps {
                cleanWs()
                echo "Workspace cleaned"
            }
        }

        stage('Environment variables') {
            steps {
                // Création des fichiers env
                script {
                    def drupalContent = ''
                    def pythonContent = ''
                    withCredentials([file(credentialsId: drupal-env, variable: 'DRUPAL_FILE')]) {
                        drupalContent = readFile(file: "${env.DRUPAL_FILE}")
                    }
                    writeFile(file: 'drupal/.env', text: drupalContent)

                    withCredentials([file(credentialsId: python-env, variable: 'PYTHON_FILE')]) {
                        pythonContent = readFile(file: "${env.PYTHON_FILE}")
                    }
                    writeFile(file: 'python/.env', text: pythonContent)

                    sh 'cat drupal/.env'
                }
                echo "Environement variables created"
            }
        }

        stage('Monolith launch') {
            steps {
                //  Lancement drupal

                echo "Drupal is ready"
            }
        }

        stage('Application tests') {
            steps {
                // Tests unitaires

                echo "Tests passed"
            }
        }

        stage('Deployment') {
            steps {
                // Lancement de l'app

                echo "Microservice deployed sucessfully"
            }
        }

    }
}
